@startuml
actor Usuario
participant "AuthenticationController" as Controller
participant "UserService" as Service
participant "UserRepository" as Repository
participant "Banco de Dados" as DB

Usuario -> Controller : POST /auth/register (UserRegisterDTO)
Controller -> Service : createUser(User)
Service -> Repository : save(User)
Repository -> DB : Insert User
DB -> Repository : Confirmação
Repository -> Service : Retorno do User
Service -> Controller : User cadastrado
Controller -> Usuario : HTTP 200 OK (User)
note right of Controller : Se o usuário já existir, retorna erro 400.
@enduml